const Map<String, String> enUS = {
  // //
  'ok': 'OK',
  'cancel':'cancel',
  'delete':'delete',
  'hello':'Hello',
  // SIGN IN PAGE
  'title': 'Hello, Again',
  'subtitle': 'Welcome back, you\'ve been missed',
  'user_name': 'Your Name',
  'name_empty': 'Please enter your name',
  'name_invalid': 'Invalid name',
  'name_hint': 'name',
  'email': 'Email Address',
  'email_hint': 'Enter your email',
  'email_empty': 'Please enter your email',
  'email_invalid': 'Invalid email address',
  'password': 'Password',
  'password_hint': 'Enter your password',
  'password_empty': 'Please enter your password',
  'recovery_password': 'Recovery Password',
  'sign_in': 'Sign In',
  'dont_have_account': 'Don\'t have an account?',
  'have_account': 'Already Have An Account?',
  'sign_up': 'Sign Up',
  'create_account': "Create Account",
  'create_account_subtitle': 'Let\'s Create Account Together',
  'admin_c_title': 'Connect With Admin',
  'admin_c_subtitle': '"Contact the admin to confirm the tariff"',
  //TARIFF PAGE
  'tariff_title': 'Tariffs',
  'tariff_subtitle': 'Choose your tariff',
  'tariff_buy': "Buy now",
  'tariff_limit_title': 'Tariff Limit',
  'tariff_limit_subtitle':
      'Your store addition limit for the tariff has been reached',
  //STORE PAGE
  'store_title': "Your Stores",
  'store_subtitle': 'To add a store, click the add button below.',
  'store_create': 'Create Your Store',
  'store_name': 'Store Name',
  'store_location': 'Store Location',
  'store_name_add': 'Enter name',
  'store_location_add': 'Enter location',
  'shop_delete_title': 'Delete',
  'shop_delete_description': 'Should the store be deleted ?',
  'home_title':'Home Page',
  // Colour names
  'colour':'Colour',
  'select_colour':'Select a colour',
  'color_black': 'Black',
  'color_white': 'White',
  'color_red': 'Red',
  'color_blue': 'Blue',
  'color_green': 'Green',
  'color_gold': 'Gold',
  'color_silver': 'Silver',
  'color_pink': 'Pink',
  'color_purple': 'Purple',
  'color_orange': 'Orange',
  'color_yellow': 'Yellow',
  'color_gray': 'Gray',
  'color_navy': 'Navy',
  'color_rose_gold': 'Rose Gold',
  'color_champagne': 'Champagne',
  //Company
  'company':'Company',
  'enter_company':'Enter company',
  'select_company':'Select a company',
  'not_select_company':'No companies available',
  //IMEI
  'imei':'Imei',
  'select_imei':'Select IMEI count',
  //Mobile
  'mobile_name':'Model Name',
  'enter_model':'Enter model',
  'status':'Status',
  // Phone Add Page
  'add_phone': 'Add Phone',
  'upload_image_warning': 'Please upload an image',
  'select_company_warning': 'Please select a company',
  'phone_added_success': 'Phone successfully added',
  'phone_added_error': 'An error occurred while adding the phone',
  'add': 'Add',
  'price': 'Price',
  'enter_price': 'Enter price',
  'box': 'Box',
  'box_yes': 'Yes',
  'box_no': 'No',
};
