const Map<String, String> enUS = {
  // SIGN IN PAGE
  'title': 'Hello, Again',
  'subtitle': 'Welcome back, you\'ve been missed',
  'user_name': 'Your Name',
  'name_empty': 'Please enter your name',
  'name_invalid': 'Invalid name',
  'name_hint': 'name',
  'email': 'Email Address',
  'email_hint': 'Enter your email',
  'email_empty': 'Please enter your email',
  'email_invalid': 'Invalid email address',
  'password': 'Password',
  'password_hint': 'Enter your password',
  'password_empty': 'Please enter your password',
  'recovery_password': 'Recovery Password',
  'sign_in': 'Sign In',
  'dont_have_account': 'Don\'t have an account?',
  'have_account': 'Already Have An Account?',
  'sign_up': 'Sign Up',
  'create_account' : "Create Account",
  'create_account_subtitle': 'Let\'s Create Account Together',
  //COMPANY PAGE 
  'store_title':"Your Stores",
  'store_subtitle':'To add a store, click the add button below.',
  'store_create': 'Create Your Store',
  'store_name':'Store Name',
  'store_location':'Store Location',
  'store_name_add':'Enter name',
  'store_location_add':'Enter location',
};
