 Map<String, String> kkKZ = {
  // General
  'ok': 'Жарайды',
  'cancel': 'Бас тарту',
  'config': 'Баптаулар',
  'delete': 'Жою',
  'edit': 'Өңдеу',
  'add': 'Қосу',
  'save': 'Сақтау',
  'search': 'Іздеу...',
  'hello': 'Сәлем',
  'from': 'Кімнен',
  'to': 'Кімге',

  // Sign In Page
  'sign_in_title': 'Қайтадан сәлем',
  'sign_in_subtitle': 'Қош келдіңіз, сізді сағындық',
  'sign_in': 'Кіру',
  'dont_have_account': 'Есептік жазбаңыз жоқ па?',
  'sign_up': 'Тіркелу',
  'have_account': 'Есептік жазбаңыз бар ма?',
  'create_account_title': 'Есептік жазба жасау',
  'create_account_subtitle': 'Есептік жазбаны бірге жасайық',
  'user_name': 'Сіздің атыңыз',
  'name_hint': 'Ат',
  'name_empty': 'Атыңызды енгізіңіз',
  'name_invalid': 'Жарамсыз ат',
  'email': 'Электронды пошта мекенжайы',
  'email_hint': 'Электронды поштаңызды енгізіңіз',
  'email_empty': 'Электронды поштаңызды енгізіңіз',
  'email_invalid': 'Жарамсыз электронды пошта мекенжайы',
  'password': 'Құпия сөз',
  'password_hint': 'Құпия сөзіңізді енгізіңіз',
  'password_empty': 'Құпия сөзіңізді енгізіңіз',
  'recovery_password': 'Құпия сөзді қалпына келтіру',

  // Admin Connect Page
  'admin_connect_title': 'Әкімшімен байланыс',
  'admin_connect_subtitle': 'Тарифті растау үшін әкімшімен байланысыңыз',
  'contact_admin_button': 'Әкімшімен байланыс',

  // Tariff Page
  'tariff_title': 'Тарифтер',
  'tariff_subtitle': 'Тарифіңізді таңдаңыз',
  'tariff_buy': 'Қазір сатып алу',
  'tariff_limit_title': 'Тариф шегі',
  'tariff_limit_subtitle': 'Сіздің тарифіңіз үшін дүкен қосу шегіне жетті',

  // Store Page
  'store_title': 'Сіздің дүкендеріңіз',
  'store_subtitle': 'Дүкен қосу үшін төмендегі батырманы басыңыз.',
  'store_create': 'Дүкеніңізді жасаңыз',
  'store_name': 'Дүкен атауы',
  'store_location': 'Дүкен орналасқан жері',
  'store_name_add': 'Атауын енгізіңіз',
  'store_location_add': 'Орналасқан жерін енгізіңіз',
  'shop_delete_title': 'Жою',
  'shop_delete_description': 'Дүкен жойылсын ба?',

  // Home Page
  'home_title': 'Басты бет',
  'search_phone': 'Модель іздеу',
  'add_phone_title': 'Телефон қосу',
  'add_accessory_title': 'Аксессуар қосу',
  'no_store_selected': 'Дүкен таңдалмады',

  // Phone Add Page
  'add_phone': 'Телефон қосу',
  'phone_add_true': 'Телефон қосылды',
  'phone_added_success': 'Телефон сәтті қосылды',
  'phone_add_false': 'Телефон қатесі',
  'phone_added_error': 'Телефон қосуда қате кетті',
  'add_press': 'Ақпарат қосу үшін + батырмасын басыңыз',
  'upload_image_warning': 'Суретті жүктеңіз',
  'image_upload_error': 'Суретті жүктеуде қате кетті',

  // Phone Info
  'mobile_name': 'Модель атауы',
  'enter_model': 'Модельді енгізіңіз',
  'imei': 'IMEI',
  'select_imei': 'IMEI санын таңдаңыз',
  'status': 'Күйі',
  'unknown': 'Белгісіз',
  'memory': 'Жады',
  'select_memory': 'Жадыны таңдаңыз',
  'please_select_memory': 'Жадыны таңдаңыз',
  'yomkist': 'Сыйымдылық',
  'ram': 'Жедел жады',
  'box': 'Қорап',
  'box_yes': 'Иә',
  'box_no': 'Жоқ',
  'buy_price': 'Сатып алу бағасы',
  'cost_price': 'Өзіндік құны',
  'sale_price': 'Сату бағасы',
  'sale_price_enter': 'Сату бағасын енгізіңіз',
  'price': 'Баға',
  'enter_price': 'Бағаны енгізіңіз',
  'sale': 'Сату',
  'sale_phone': 'Телефон сату',
  'payment_type': 'Төлем түрі',
  'cash': 'Қолма-қол',
  'card': 'Карта',
  'transfer': 'Аударым',
  'invalid_number': 'Жарамсыз сан',

  // Accessory
  'sell_accessory': 'Аксессуар сату',
  'quantity': 'Саны',
  'quantity_must_be_positive': 'Саны 0-ден жоғары болуы керек',
  'accessory_sold_success': 'Аксессуар сәтті сатылды',
  'accessory_sold_failed': 'Аксессуар сату сәтсіз аяқталды',
  'are_you_sure_delete_accessory': 'Бул аксессуарды өчүрүүнү каалайсызбы?',

  // Company
  'company': 'Компания',
  'enter_company': 'Компанияны енгізіңіз',
  'select_company': 'Компанияны таңдаңыз',
  'select_company_warning': 'Компанияны таңдаңыз',
  'not_select_company': 'Компаниялар қолжетімді емес',

  // Colors
  'colour': 'Түс',
  'select_colour': 'Түсті таңдаңыз',
  'color_black': 'Қара',
  'color_white': 'Ақ',
  'color_red': 'Қызыл',
  'color_blue': 'Көк',
  'color_green': 'Жасыл',
  'color_gold': 'Алтын',
  'color_silver': 'Күміс',
  'color_pink': 'Қызғылт',
  'color_purple': 'Күлгін',
  'color_orange': 'Қызғылт сары',
  'color_yellow': 'Сары',
  'color_gray': 'Сұр',
  'color_navy': 'Қою көк',
  'color_rose_gold': 'Қызғылт алтын',
  'color_champagne': 'Шампан',

  // Edit User Info
  'edit_account': 'Есептік жазбаны өңдеу',
  'enter_name': 'Атты енгізіңіз',
  'enter_email': 'Электронды поштаны енгізіңіз',
  'invalid_email_format': 'Жарамсыз электронды пошта форматы',
  'enter_new_password_optional': 'Жаңа құпия сөзді енгізіңіз (міндетті емес)',
  'password_too_short': 'Құпия сөз кем дегенде 6 таңбадан тұруы керек',
  'user_info_updated': '✅ Пайдаланушы ақпараты сәтті жаңартылды',
  'user_info_update_error': '❌ Қате: ',
  'profile': 'Профиль',

  // Report Page
  'report_title': 'Телефон табысы туралы есеп',
  'total_phones': 'Телефондар',
  'total_accessories': 'Аксессуарлар',
  'phone_profit_chart': 'Телефон табысының диаграммасы',
  'accessory_profit_chart': 'Аксессуар табысының диаграммасы',
  'top_selling_phones': 'Ең көп сатылған телефондар',
  'top_selling_accessories': 'Ең көп сатылған аксессуарлар',
  'no_data_available': 'Деректер жоқ',
  'currency_suffix': 'теңге',
  'total_profit': 'Жалпы табыс',
  "no_permission": "Рұқсат жоқ",
  "no_accessory_permission_message":
      "Сізде аксессуарлар қосуға рұқсат жоқ. Тарифіңізді жаңартыңыз.",

  // Settings
  'app_setting': 'Қосымша баптаулары',
  "account_settings": "Есептік Жазба Параметрлері",
  'setting_and_account': 'Баптаулар және есептік жазба',
  'setting': 'Баптаулар',
  'dark_mode': 'Қараңғы режим',
  'language': 'Тіл',
  'currency': 'Валюта',
  'tariffs': 'Тарифтер',
  'aboutApp': 'Қосымша туралы',
  'signOut': 'Шығу',

  // Generic Error
  'error_generic': 'Бірдеңе дұрыс болмады. Қайтадан көріңіз.',
};
