const Map<String, String> kyKY = {
  // General
  'ok': 'ОК',
  'cancel': 'Жокко чыгаруу',
  'config': 'Жөндөөлөр',
  'delete': 'Өчүрүү',
  'edit': 'Оңдоо',
  'add': 'Кошуу',
  'save': 'Сактоо',
  'search': 'Издөө...',
  'hello': 'Салам',
  'from': 'Кимден',
  'to': 'Кимге',

  // Sign In Page
  'sign_in_title': 'Кайрадан салам',
  'sign_in_subtitle': 'Кош келиңиз, сизди сагындык',
  'sign_in': 'Кирүү',
  'dont_have_account': 'Аккаунтуңуз жокпу?',
  'sign_up': 'Катталуу',
  'have_account': 'Аккаунтуңуз барбы?',
  'create_account_title': 'Аккаунт түзүү',
  'create_account_subtitle': 'Келиңиз, аккаунтту чогуу түзөлү',
  'user_name': 'Сиздин атыңыз',
  'name_hint': 'Ат',
  'name_empty': 'Сураныч, атыңызды киргизиңиз',
  'name_invalid': 'Туура эмес ат',
  'email': 'Электрондук почта дареги',
  'email_hint': 'Электрондук почтаңызды киргизиңиз',
  'email_empty': 'Сураныч, электрондук почтаңызды киргизиңиз',
  'email_invalid': 'Туура эмес электрондук почта дареги',
  'password': 'Сырсөз',
  'password_hint': 'Сырсөзүңүздү киргизиңиз',
  'password_empty': 'Сураныч, сырсөзүңүздү киргизиңиз',
  'recovery_password': 'Сырсөздү калыбына келтирүү',

  // Admin Connect Page
  'admin_connect_title': 'Администратор менен байланышуу',
  'admin_connect_subtitle':
      'Тарифти ырастоо үчүн администратор менен байланышыңыз',
  'contact_admin_button': 'Администратор менен байланышуу',

  // Tariff Page
  'tariff_title': 'Тарифтер',
  'tariff_subtitle': 'Тарифиңизди тандаңыз',
  'tariff_buy': 'Азыр сатып алуу',
  'tariff_limit_title': 'Тариф чегиндери',
  'tariff_limit_subtitle': 'Сиздин тариф үчүн дүкөн кошуу чегине жетти',

  // Store Page
  'store_title': 'Сиздин дүкөндөрүңүз',
  'store_subtitle': 'Дүкөн кошуу үчүн төмөндөгү баскычты басыңыз.',
  'store_create': 'Дүкөнүңүздү түзүңүз',
  'store_name': 'Дүкөн аты',
  'store_location': 'Дүкөн жайгашкан жери',
  'store_name_add': 'Атын киргизиңиз',
  'store_location_add': 'Жайгашкан жерин киргизиңиз',
  'shop_delete_title': 'Өчүрүү',
  'shop_delete_description': 'Дүкөн өчүрүлсүнбү?',

  // Home Page
  'home_title': 'Башкы бет',
  'search_phone': 'Модель издөө',
  'add_phone_title': 'Телефон кошуу',
  'add_accessory_title': 'Аксессуар кошуу',
  'no_store_selected': 'Дүкөн тандалган жок',

  // Phone Add Page
  'add_phone': 'Телефон кошуу',
  'phone_add_true': 'Телефон кошулду',
  'phone_added_success': 'Телефон ийгиликтүү кошулду',
  'phone_add_false': 'Телефон катасы',
  'phone_added_error': 'Телефон кошууда ката кетти',
  'add_press': 'Маалымат кошуу үчүн + баскычын басыңыз',
  'upload_image_warning': 'Сураныч, сүрөт жүктөңүз',
  'image_upload_error': 'Сүрөт жүктөөдө ката кетти',

  // Phone Info
  'mobile_name': 'Модель аты',
  'enter_model': 'Модель киргизиңиз',
  'imei': 'IMEI',
  'select_imei': 'IMEI санын тандаңыз',
  'status': 'Абалы',
  'unknown': 'Белгисиз',
  'memory': 'Эс тутуму',
  'select_memory': 'Эс тутумун тандаңыз',
  'please_select_memory': 'Сураныч, эс тутумун тандаңыз',
  'yomkist': 'Сыйымдуулук',
  'ram': 'Оперативдик эс',
  'box': 'Коробка',
  'box_yes': 'Ооба',
  'box_no': 'Жок',
  'buy_price': 'Сатып алуу баасы',
  'cost_price': 'Өзүнө кеткен чыгым',
  'sale_price': 'Сатуу баасы',
  'sale_price_enter': 'Сураныч, сатуу баасын киргизиңиз',
  'price': 'Баасы',
  'enter_price': 'Бааны киргизиңиз',
  'sale': 'Сатуу',
  'sale_phone': 'Телефон сатуу',
  'payment_type': 'Төлөм түрү',
  'cash': 'Накталай',
  'card': 'Карта',
  'transfer': 'Которуу',
  'invalid_number': 'Туура эмес сан',

  // Accessory
  'sell_accessory': 'Аксессуар сатуу',
  'quantity': 'Саны',
  'quantity_must_be_positive': 'Саны 0дон чоң болушу керек',
  'accessory_sold_success': 'Аксессуар ийгиликтүү сатылды',
  'accessory_sold_failed': 'Аксессуар сатуу ишке ашкан жок',
  'are_you_sure_delete_accessory': 'Бул аксессуарды өчүрүүнү каалайсызбы?',

  // Company
  'company': 'Компания',
  'enter_company': 'Компанияны киргизиңиз',
  'select_company': 'Компанияны тандаңыз',
  'select_company_warning': 'Сураныч, компанияны тандаңыз',
  'not_select_company': 'Компаниялар жеткиликтүү эмес',

  // Colors
  'colour': 'Түс',
  'select_colour': 'Түс тандаңыз',
  'color_black': 'Кара',
  'color_white': 'Ак',
  'color_red': 'Кызыл',
  'color_blue': 'Көк',
  'color_green': 'Жашыл',
  'color_gold': 'Алтын',
  'color_silver': 'Күмүш',
  'color_pink': 'Кызгылт',
  'color_purple': 'Кочкул',
  'color_orange': 'Кызгылт сары',
  'color_yellow': 'Сары',
  'color_gray': 'Боз',
  'color_navy': 'Кочкул көк',
  'color_rose_gold': 'Кызгылт алтын',
  'color_champagne': 'Шампан',

  // Edit User Info
  'edit_account': 'Аккаунтту оңдоо',
  'enter_name': 'Атты киргизиңиз',
  'enter_email': 'Электрондук почтаны киргизиңиз',
  'invalid_email_format': 'Туура эмес электрондук почта форматы',
  'enter_new_password_optional': 'Жаңы сырсөздү киргизиңиз (милдеттүү эмес)',
  'password_too_short': 'Сырсөз кеминде 6 белгиден турушу керек',
  'user_info_updated': '✅ Колдонуучу маалыматы ийгиликтүү жаңыртылды',
  'user_info_update_error': '❌ Ката: ',
  'profile': 'Профиль',

  // Report Page
  'report_title': 'Телефон кирешелери боюнча отчет',
  'total_phones': 'Телефондор',
  'total_accessories': 'Аксессуарлар',
  'phone_profit_chart': 'Телефон кирешесинин диаграммасы',
  'accessory_profit_chart': 'Аксессуар кирешесинин диаграммасы',
  'top_selling_phones': 'Эң көп сатылган телефондор',
  'top_selling_accessories': 'Эң көп сатылган аксессуарлар',
  'no_data_available': 'Маалымат жок',
  'currency_suffix': 'сом',
  'total_profit': 'Жалпы киреше',
  "no_permission": "Уруксат жок",
  "no_accessory_permission_message": "Сизде аксессуарларды кошууга уруксат жок. Сураныч, тарифиңизди жаңыртыңыз.",

  // Settings
  'app_setting': 'Колдонмо жөндөөлөрү',
  "account_settings": "Эсеп Жөндөөлөрү",
  'setting_and_account': 'Жөндөөлөр жана аккаунт',
  'setting': 'Жөндөөлөр',
  'dark_mode': 'Караңгы режим',
  'language': 'Тил',
  'currency': 'Валюта',
  'tariffs': 'Тарифтер',
  'aboutApp': 'Колдонмо жөнүндө',
  'signOut': 'Чыгуу',

  // Generic Error
  'error_generic': 'Бир нерсе туура эмес болду. Сураныч, кайра аракет кылыңыз.',
};
