// Russian
const Map<String, String> ruRU = {
  'ok': 'OK',
  'cancel': 'Отмена',
  'delete': 'Удалить',
  'hello': 'Привет',
  // SIGN IN PAGE
  'title': 'Снова привет',
  'subtitle': 'С возвращением, мы скучали',
  'user_name': 'Ваше имя',
  'name_empty': 'Пожалуйста, введите имя',
  'name_invalid': 'Неверное имя',
  'name_hint': 'Имя',
  'email': 'Адрес электронной почты',
  'email_hint': 'Введите email',
  'email_empty': 'Пожалуйста, введите email',
  'email_invalid': 'Неверный адрес email',
  'password': 'Пароль',
  'password_hint': 'Введите пароль',
  'password_empty': 'Пожалуйста, введите пароль',
  'recovery_password': 'Восстановление пароля',
  'sign_in': 'Войти',
  'dont_have_account': 'Нет аккаунта?',
  'have_account': 'Уже есть аккаунт?',
  'sign_up': 'Регистрация',
  'create_account': "Создать аккаунт",
  'create_account_subtitle': 'Давайте создадим аккаунт вместе',
  'admin_c_title': 'Связаться с админом',
  'admin_c_subtitle': '"Свяжитесь с админом для подтверждения тарифа"',
  // TARIFF PAGE
  'tariff_title': 'Тарифы',
  'tariff_subtitle': 'Выберите тариф',
  'tariff_buy': "Купить",
  'tariff_limit_title': 'Лимит тарифа',
  'tariff_limit_subtitle': 'Лимит добавления магазинов для тарифа достигнут',
  // STORE PAGE
  'store_title': "Ваши магазины",
  'store_subtitle': 'Чтобы добавить магазин, нажмите кнопку ниже.',
  'store_create': 'Создать магазин',
  'store_name': 'Название магазина',
  'store_location': 'Местоположение магазина',
  'store_name_add': 'Введите название',
  'store_location_add': 'Введите местоположение',
  'shop_delete_title': 'Удалить',
  'shop_delete_description': 'Удалить магазин?',
  'home_title':'Домашняя страница',
};