const Map<String, String> ruRU = {
  // General
  'ok': 'ОК',
  'cancel': 'Отмена',
  'config': 'Настройки',
  'delete': 'Удалить',
  'edit': 'Редактировать',
  'add': 'Добавить',
  'save': 'Сохранить',
  'search': 'Поиск...',
  'hello': 'Привет',
  'from': 'От',
  'to': 'До',

  // Sign In Page
  'sign_in_title': 'С возвращением',
  'sign_in_subtitle': 'Добро пожаловать, мы скучали по вам',
  'sign_in': 'Войти',
  'dont_have_account': 'Нет аккаунта?',
  'sign_up': 'Зарегистрироваться',
  'have_account': 'Уже есть аккаунт?',
  'create_account_title': 'Создать аккаунт',
  'create_account_subtitle': 'Давай создадим аккаунт вместе',
  'user_name': 'Ваше имя',
  'name_hint': 'Имя',
  'name_empty': 'Пожалуйста, введите ваше имя',
  'name_invalid': 'Недопустимое имя',
  'email': 'Адрес электронной почты',
  'email_hint': 'Введите ваш email',
  'email_empty': 'Пожалуйста, введите ваш email',
  'email_invalid': 'Недопустимый адрес электронной почты',
  'password': 'Пароль',
  'password_hint': 'Введите ваш пароль',
  'password_empty': 'Пожалуйста, введите ваш пароль',
  'recovery_password': 'Восстановить пароль',

  // Admin Connect Page
  'admin_connect_title': 'Связаться с администратором',
  'admin_connect_subtitle':
      'Свяжитесь с администратором для подтверждения тарифа',
  'contact_admin_button': 'Связаться с администратором',

  // Tariff Page
  'tariff_title': 'Тарифы',
  'tariff_subtitle': 'Выберите ваш тариф',
  'tariff_buy': 'Купить сейчас',
  'tariff_limit_title': 'Лимит тарифа',
  'tariff_limit_subtitle':
      'Достигнут лимит добавления магазинов для вашего тарифа',

  // Store Page
  'store_title': 'Ваши магазины',
  'store_subtitle': 'Чтобы добавить магазин, нажмите кнопку ниже.',
  'store_create': 'Создать ваш магазин',
  'store_name': 'Название магазина',
  'store_location': 'Местоположение магазина',
  'store_name_add': 'Введите название',
  'store_location_add': 'Введите местоположение',
  'shop_delete_title': 'Удалить',
  'shop_delete_description': 'Удалить магазин?',

  // Home Page
  'home_title': 'Главная страница',
  'search_phone': 'Поиск модели',
  'add_phone_title': 'Добавить телефон',
  'add_accessory_title': 'Добавить аксессуар',
  'no_store_selected': 'Магазин не выбран',

  // Phone Add Page
  'add_phone': 'Добавить телефон',
  'phone_add_true': 'Телефон добавлен',
  'phone_added_success': 'Телефон успешно добавлен',
  'phone_add_false': 'Ошибка телефона',
  'phone_added_error': 'Произошла ошибка при добавлении телефона',
  'add_press': 'Нажмите + для добавления информации',
  'upload_image_warning': 'Пожалуйста, загрузите изображение',
  'image_upload_error': 'Произошла ошибка при загрузке изображения',

  // Phone Info
  'mobile_name': 'Название модели',
  'enter_model': 'Введите модель',
  'imei': 'IMEI',
  'select_imei': 'Выберите количество IMEI',
  'status': 'Статус',
  'unknown': 'Неизвестно',
  'memory': 'Память',
  'select_memory': 'Выберите память',
  'please_select_memory': 'Пожалуйста, выберите память',
  'yomkist': 'Емкость',
  'ram': 'Оперативная память',
  'box': 'Коробка',
  'box_yes': 'Да',
  'box_no': 'Нет',
  'buy_price': 'Цена покупки',
  'cost_price': 'Себестоимость',
  'sale_price': 'Цена продажи',
  'sale_price_enter': 'Пожалуйста, введите цену продажи',
  'price': 'Цена',
  'enter_price': 'Введите цену',
  'sale': 'Продажа',
  'sale_phone': 'Продать телефон',
  'payment_type': 'Тип оплаты',
  'cash': 'Наличные',
  'card': 'Карта',
  'transfer': 'Перевод',
  'invalid_number': 'Недопустимый номер',

  // Accessory
  'sell_accessory': 'Продать аксессуар',
  'quantity': 'Количество',
  'quantity_must_be_positive': 'Количество должно быть больше 0',
  'accessory_sold_success': 'Аксессуар успешно продан',
  'accessory_sold_failed': 'Не удалось продать аксессуар',
  'are_you_sure_delete_accessory':
      'Вы уверены, что хотите удалить этот аксессуар?',

  // Company
  'company': 'Компания',
  'enter_company': 'Введите компанию',
  'select_company': 'Выберите компанию',
  'select_company_warning': 'Пожалуйста, выберите компанию',
  'not_select_company': 'Компании недоступны',

  // Colors
  'colour': 'Цвет',
  'select_colour': 'Выберите цвет',
  'color_black': 'Чёрный',
  'color_white': 'Белый',
  'color_red': 'Красный',
  'color_blue': 'Синий',
  'color_green': 'Зелёный',
  'color_gold': 'Золотой',
  'color_silver': 'Серебряный',
  'color_pink': 'Розовый',
  'color_purple': 'Фиолетовый',
  'color_orange': 'Оранжевый',
  'color_yellow': 'Жёлтый',
  'color_gray': 'Серый',
  'color_navy': 'Тёмно-синий',
  'color_rose_gold': 'Розовое золото',
  'color_champagne': 'Шампань',

  // Edit User Info
  'edit_account': 'Редактировать аккаунт',
  'enter_name': 'Введите имя',
  'enter_email': 'Введите email',
  'invalid_email_format': 'Недопустимый формат email',
  'enter_new_password_optional': 'Введите новый пароль (опционально)',
  'password_too_short': 'Пароль должен содержать не менее 6 символов',
  'user_info_updated': '✅ Информация пользователя успешно обновлена',
  'user_info_update_error': '❌ Ошибка: ',
  'profile': 'Профиль',

  // Report Page
  'report_title': 'Отчёт о доходах',
  'total_phones': 'Телефоны',
  'total_accessories': 'Аксессуары',
  'phone_profit_chart': 'График прибыли от телефонов',
  'accessory_profit_chart': 'График прибыли от аксессуаров',
  'top_selling_phones': 'Самые продаваемые телефоны',
  'top_selling_accessories': 'Самые продаваемые аксессуары',
  'no_data_available': 'Данные отсутствуют',
  'currency_suffix': 'сум',
  'total_profit': 'Общая прибыль',
  "no_permission": "Нет разрешения",
  "no_accessory_permission_message": "У вас нет разрешения на добавление аксессуаров. Пожалуйста, обновите ваш тариф.",

  // Settings
  'app_setting': 'Настройки приложения',
  "account_settings": "Настройки аккаунта",
  'setting_and_account': 'Настройки и аккаунт',
  'setting': 'Настройки',
  'dark_mode': 'Тёмный режим',
  'language': 'Язык',
  'currency': 'Валюта',
  'tariffs': 'Тарифы',
  'aboutApp': 'О приложении',
  'signOut': 'Выйти',

  // Generic Error
  'error_generic': 'Что-то пошло не так. Пожалуйста, попробуйте снова.',
};
