// Russian
const Map<String, String> ruRU = {
  'ok': 'OK',
  'cancel': 'Отмена',
  'delete': 'Удалить',
  'hello': 'Привет',
  // SIGN IN PAGE
  'title': 'Снова привет',
  'subtitle': 'С возвращением, мы скучали',
  'user_name': 'Ваше имя',
  'name_empty': 'Пожалуйста, введите имя',
  'name_invalid': 'Неверное имя',
  'name_hint': 'Имя',
  'email': 'Адрес электронной почты',
  'email_hint': 'Введите email',
  'email_empty': 'Пожалуйста, введите email',
  'email_invalid': 'Неверный адрес email',
  'password': 'Пароль',
  'password_hint': 'Введите пароль',
  'password_empty': 'Пожалуйста, введите пароль',
  'recovery_password': 'Восстановление пароля',
  'sign_in': 'Войти',
  'dont_have_account': 'Нет аккаунта?',
  'have_account': 'Уже есть аккаунт?',
  'sign_up': 'Регистрация',
  'create_account': "Создать аккаунт",
  'create_account_subtitle': 'Давайте создадим аккаунт вместе',
  'admin_c_title': 'Связаться с админом',
  'admin_c_subtitle': '"Свяжитесь с админом для подтверждения тарифа"',
  // TARIFF PAGE
  'tariff_title': 'Тарифы',
  'tariff_subtitle': 'Выберите тариф',
  'tariff_buy': "Купить",
  'tariff_limit_title': 'Лимит тарифа',
  'tariff_limit_subtitle': 'Лимит добавления магазинов для тарифа достигнут',
  // STORE PAGE
  'store_title': "Ваши магазины",
  'store_subtitle': 'Чтобы добавить магазин, нажмите кнопку ниже.',
  'store_create': 'Создать магазин',
  'store_name': 'Название магазина',
  'store_location': 'Местоположение магазина',
  'store_name_add': 'Введите название',
  'store_location_add': 'Введите местоположение',
  'shop_delete_title': 'Удалить',
  'shop_delete_description': 'Удалить магазин?',
  'home_title':'Домашняя страница',

  // Colour names
  'colour':'Цвет',
  'select_colour':'Выберите цвет',
  'color_black': 'Черный',
  'color_white': 'Белый',
  'color_red': 'Красный',
  'color_blue': 'Синий',
  'color_green': 'Зеленый',
  'color_gold': 'Золотой',
  'color_silver': 'Серебряный',
  'color_pink': 'Розовый',
  'color_purple': 'Фиолетовый',
  'color_orange': 'Оранжевый',
  'color_yellow': 'Желтый',
  'color_gray': 'Серый',
  'color_navy': 'Тёмно-синий',
  'color_rose_gold': 'Розовое золото',
  'color_champagne': 'Шампанское',

  // Company
  'company':'Компания',
  'enter_company':'Введите компанию',
  'select_company':'Выберите компанию',
  'not_select_company':'Нет доступных компаний',

  // IMEI
  'imei':'IMEI',
  'select_imei':'Выберите количество IMEI',

  // Mobile
  'mobile_name':'Модель',
  'enter_model':'Введите модель',
  'status':'Статус',

  // Phone Add Page
  'add_phone': 'Добавить телефон',
  'upload_image_warning': 'Пожалуйста, загрузите изображение',
  'select_company_warning': 'Пожалуйста, выберите компанию',
  'phone_added_success': 'Телефон успешно добавлен',
  'phone_added_error': 'Произошла ошибка при добавлении телефона',
  'add': 'Добавить',
  'price': 'Цена',
  'enter_price': 'Введите цену',
  'box': 'Коробка',
  'box_yes': 'Да',
  'box_no': 'Нет',
  'add_press':'Нажмите + для добавления информации',

  // Phone info
  'yomkis': 'Ёмкость',
  'sale': 'Продажа',
};