const Map<String, String> tjTJ = {
  // General
  'ok': 'Хуб',
  'cancel': 'Бекор кардан',
  'config': 'Танзимот',
  'delete': 'Нест кардан',
  'edit': 'Таҳрир',
  'add': 'Илова кардан',
  'save': 'Нигоҳ доштан',
  'search': 'Ҷустуҷӯ...',
  'hello': 'Салом',
  'from': 'Аз',
  'to': 'Ба',

  // Sign In Page
  'sign_in_title': 'Боз салом',
  'sign_in_subtitle': 'Хуш омадед, мо шуморо пазмон шудем',
  'sign_in': 'Ворид шудан',
  'dont_have_account': 'Ҳисоб надоред?',
  'sign_up': 'Сабти ном',
  'have_account': 'Аллакай ҳисоб доред?',
  'create_account_title': 'Сохтани ҳисоб',
  'create_account_subtitle': 'Биёед, якҷоя ҳисоб эҷод кунем',
  'user_name': 'Номи шумо',
  'name_hint': 'Ном',
  'name_empty': 'Лутфан, номи худро ворид кунед',
  'name_invalid': 'Номи нодуруст',
  'email': 'Суроғаи почтаи электронӣ',
  'email_hint': 'Почтаи электронии худро ворид кунед',
  'email_empty': 'Лутфан, почтаи электронии худро ворид кунед',
  'email_invalid': 'Суроғаи почтаи электронии нодуруст',
  'password': 'Рамз',
  'password_hint': 'Рамзи худро ворид кунед',
  'password_empty': 'Лутфан, рамзи худро ворид кунед',
  'recovery_password': 'Барқароркунии рамз',

  // Admin Connect Page
  'admin_connect_title': 'Пайваст бо администратор',
  'admin_connect_subtitle': 'Бо администратор барои тасдиқи тариф тамос кунед',
  'contact_admin_button': 'Тамос бо администратор',

  // Tariff Page
  'tariff_title': 'Тарифҳо',
  'tariff_subtitle': 'Тарифи худро интихоб кунед',
  'tariff_buy': 'Ҳоло харидан',
  'tariff_limit_title': 'Маҳдудияти тариф',
  'tariff_limit_subtitle':
      'Маҳдудияти илова кардани мағоза барои тарифи шумо расидааст',

  // Store Page
  'store_title': 'Мағозаҳои шумо',
  'store_subtitle': 'Барои илова кардани мағоза, тугмаи зерро пахш кунед.',
  'store_create': 'Мағозаи худро созед',
  'store_name': 'Номи мағоза',
  'store_location': 'Ҷойгиршавии мағоза',
  'store_name_add': 'Номро ворид кунед',
  'store_location_add': 'Ҷойгиршавиро ворид кунед',
  'shop_delete_title': 'Нест кардан',
  'shop_delete_description': 'Оё мағоза нест карда шавад?',

  // Home Page
  'home_title': 'Саҳифаи асосӣ',
  'search_phone': 'Ҷустуҷӯи модел',
  'add_phone_title': 'Илова кардани телефон',
  'add_accessory_title': 'Илова кардани аксессуар',
  'no_store_selected': 'Мағоза интихоб нашудааст',

  // Phone Add Page
  'add_phone': 'Илова кардани телефон',
  'phone_add_true': 'Телефон илова шуд',
  'phone_added_success': 'Телефон бомуваффақият илова шуд',
  'phone_add_false': 'Хатои телефон',
  'phone_added_error': 'Ҳангоми илова кардани телефон хато рух дод',
  'add_press': 'Барои илова кардани маълумот + -ро пахш кунед',
  'upload_image_warning': 'Лутфан, тасвир бор кунед',
  'image_upload_error': 'Ҳангоми бор кардани тасвир хато рух дод',

  // Phone Info
  'mobile_name': 'Номи модел',
  'enter_model': 'Моделро ворид кунед',
  'imei': 'IMEI',
  'select_imei': 'Шумораи IMEI-ро интихоб кунед',
  'status': 'Вазъият',
  'unknown': 'Номаълум',
  'memory': 'Ҳофиза',
  'select_memory': 'Ҳофиза интихоб кунед',
  'please_select_memory': 'Лутфан, ҳофиза интихоб кунед',
  'yomkist': 'Иқтидор',
  'ram': 'Ҳофизаи оперативӣ',
  'box': 'Қуттӣ',
  'box_yes': 'Ҳа',
  'box_no': 'Не',
  'buy_price': 'Нархи харид',
  'cost_price': 'Арзиши аслӣ',
  'sale_price': 'Нархи фурӯш',
  'sale_price_enter': 'Лутфан, нархи фурӯшро ворид кунед',
  'price': 'Нарх',
  'enter_price': 'Нархро ворид кунед',
  'sale': 'Фурӯш',
  'sale_phone': 'Фурӯши телефон',
  'payment_type': 'Навъи пардохт',
  'cash': 'Нақд',
  'card': 'Корт',
  'transfer': 'Интиқол',
  'invalid_number': 'Рақами нодуруст',

  // Accessory
  'sell_accessory': 'Фурӯши аксессуар',
  'quantity': 'Миқдор',
  'quantity_must_be_positive': 'Миқдор бояд аз 0 зиёд бошад',
  'accessory_sold_success': 'Аксессуар бомуваффақият фурӯхта шуд',
  'accessory_sold_failed': 'Фурӯши аксессуар амалӣ нашуд',
  'are_you_sure_delete_accessory':
      'Шумо мутмаин ҳастед, ки ин лавозимотро нест кардан мехоҳед?',

  // Company
  'company': 'Ширкат',
  'enter_company': 'Ширкатро ворид кунед',
  'select_company': 'Ширкатро интихоб кунед',
  'select_company_warning': 'Лутфан, ширкатро интихоб кунед',
  'not_select_company': 'Ширкатҳо дастрас нестанд',

  // Colors
  'colour': 'Ранг',
  'select_colour': 'Ранг интихоб кунед',
  'color_black': 'Сиёҳ',
  'color_white': 'Сафед',
  'color_red': 'Сурх',
  'color_blue': 'Кабуд',
  'color_green': 'Сабз',
  'color_gold': 'Тиллоӣ',
  'color_silver': 'Нуқрагин',
  'color_pink': 'Гулобӣ',
  'color_purple': 'Бунафш',
  'color_orange': 'Норинҷӣ',
  'color_yellow': 'Зард',
  'color_gray': 'Хокистарӣ',
  'color_navy': 'Кабуди тира',
  'color_rose_gold': 'Тиллои гулобӣ',
  'color_champagne': 'Шампан',

  // Edit User Info
  'edit_account': 'Таҳрири ҳисоб',
  'enter_name': 'Номро ворид кунед',
  'enter_email': 'Почтаи электрониро ворид кунед',
  'invalid_email_format': 'Формати почтаи электронии нодуруст',
  'enter_new_password_optional': 'Рамзи навро ворид кунед (ихтиёрӣ)',
  'password_too_short': 'Рамз бояд на камтар аз 6 аломат бошад',
  'user_info_updated': '✅ Маълумоти корбар бомуваффақият навсозӣ шуд',
  'user_info_update_error': '❌ Хато: ',
  'profile': 'Профил',

  // Report Page
  'report_title': 'Гузориши даромади телефонҳо',
  'total_phones': 'Телефонҳо',
  'total_accessories': 'Аксессуарҳо',
  'phone_profit_chart': 'Диаграммаи фоидаи телефонҳо',
  'accessory_profit_chart': 'Диаграммаи фоидаи аксессуарҳо',
  'top_selling_phones': 'Телефонҳои пурфурӯш',
  'top_selling_accessories': 'Аксессуарҳои пурфурӯш',
  'no_data_available': 'Маълумот дастрас нест',
  'currency_suffix': 'сум',
  'total_profit': 'Фоидаи умумӣ',
  "no_permission": "Иҷозат нест",
  "no_accessory_permission_message": "Шумо иҷозати илова кардани аксессуарҳоро надоред. Лутфан, тарифи худро навсозӣ кунед.",

  // Settings
  'app_setting': 'Танзимоти барнома',
  "account_settings": "Танзимоти Ҳисоб",
  'setting_and_account': 'Танзимот ва ҳисоб',
  'setting': 'Танзимот',
  'dark_mode': 'Реҷаи торик',
  'language': 'Забон',
  'currency': 'Асъор',
  'tariffs': 'Тарифҳо',
  'aboutApp': 'Дар бораи барнома',
  'signOut': 'Баромадан',

  // Generic Error
  'error_generic': 'Чизе нодуруст шуд. Лутфан, боз кӯшиш кунед.',
};
