const Map<String, String> uzUZ = {
  // General
  'ok': 'OK',
  'cancel': 'Bekor qilish',
  'config': 'Sozlamalar',
  'delete': 'O‘chirish',
  'edit': 'Tahrirlash',
  'add': 'Qo‘shish',
  'save': 'Saqlash',
  'search': 'Qidirish...',
  'hello': 'Salom',
  'from': 'Dan',
  'to': 'Gacha',

  // Sign In Page
  'sign_in_title': 'Yana salom',
  'sign_in_subtitle': 'Xush kelibsiz, sizni sog‘indik',
  'sign_in': 'Kirish',
  'dont_have_account': 'Hisobingiz yo‘qmi?',
  'sign_up': 'Ro‘yxatdan o‘tish',
  'have_account': 'Allaqachon hisobingiz bormi?',
  'create_account_title': 'Hisob yaratish',
  'create_account_subtitle': 'Keling, birgalikda hisob yarating',
  'user_name': 'Ismingiz',
  'name_hint': 'Ism',
  'name_empty': 'Iltimos, ismingizni kiriting',
  'name_invalid': 'Noto‘g‘ri ism',
  'email': 'Elektron pochta manzili',
  'email_hint': 'Elektron pochtangizni kiriting',
  'email_empty': 'Iltimos, elektron pochtangizni kiriting',
  'email_invalid': 'Noto‘g‘ri elektron pochta manzili',
  'password': 'Parol',
  'password_hint': 'Parolingizni kiriting',
  'password_empty': 'Iltimos, parolingizni kiriting',
  'recovery_password': 'Parolni tiklash',

  // Admin Connect Page
  'admin_connect_title': 'Administrator bilan bog‘lanish',
  'admin_connect_subtitle':
      'Tarifni tasdiqlash uchun administrator bilan bog‘laning',
  'contact_admin_button': 'Administrator bilan bog‘lanish',

  // Tariff Page
  'tariff_title': 'Tariflar',
  'tariff_subtitle': 'Tarifingizni tanlang',
  'tariff_buy': 'Hozir sotib olish',
  'tariff_limit_title': 'Tarif cheklovi',
  'tariff_limit_subtitle':
      'Sizning tarifingiz uchun do‘kon qo‘shish chegarasiga yetildi',

  // Store Page
  'store_title': 'Sizning do‘konlaringiz',
  'store_subtitle': 'Do‘kon qo‘shish uchun quyidagi tugmani bosing.',
  'store_create': 'Do‘koningizni yarating',
  'store_name': 'Do‘kon nomi',
  'store_location': 'Do‘kon manzili',
  'store_name_add': 'Nomini kiriting',
  'store_location_add': 'Manzilni kiriting',
  'shop_delete_title': 'O‘chirish',
  'shop_delete_description': 'Do‘kon o‘chirilsinmi?',

  // Home Page
  'home_title': 'Bosh sahifa',
  'search_phone': 'Model qidirish',
  'add_phone_title': 'Telefon qo‘shish',
  'add_accessory_title': 'Aksessuar qo‘shish',
  'no_store_selected': 'Do‘kon tanlanmadi',

  // Phone Add Page
  'add_phone': 'Telefon qo‘shish',
  'phone_add_true': 'Telefon qo‘shildi',
  'phone_added_success': 'Telefon muvaffaqiyatli qo‘shildi',
  'phone_add_false': 'Telefon xatosi',
  'phone_added_error': 'Telefon qo‘shishda xato yuz berdi',
  'add_press': 'Ma’lumot qo‘shish uchun + ni bosing',
  'upload_image_warning': 'Iltimos, rasm yuklang',
  'image_upload_error': 'Rasm yuklashda xato yuz berdi',

  // Phone Info
  'mobile_name': 'Model nomi',
  'enter_model': 'Modelni kiriting',
  'imei': 'IMEI',
  'select_imei': 'IMEI sonini tanlang',
  'status': 'Holati',
  'unknown': 'Noma’lum',
  'memory': 'Xotira',
  'select_memory': 'Xotirani tanlang',
  'please_select_memory': 'Iltimos, xotirani tanlang',
  'yomkist': 'Yomkis',
  'ram': 'Operativ xotira',
  'box': 'Quti',
  'box_yes': 'Ha',
  'box_no': 'Yo‘q',
  'buy_price': 'Sotib olish narxi',
  'cost_price': 'Tannarx',
  'sale_price': 'Sotish narxi',
  'sale_price_enter': 'Iltimos, sotish narxini kiriting',
  'price': 'Narx',
  'enter_price': 'Narxni kiriting',
  'sale': 'Sotish',
  'sale_phone': 'Telefon sotish',
  'payment_type': 'To‘lov turi',
  'cash': 'Naqd',
  'card': 'Karta',
  'transfer': 'O‘tkazma',
  'invalid_number': 'Noto‘g‘ri raqam',

  // Accessory
  'sell_accessory': 'Aksessuar sotish',
  'quantity': 'Soni',
  'quantity_must_be_positive': 'Soni 0 dan katta bo‘lishi kerak',
  'accessory_sold_success': 'Aksessuar muvaffaqiyatli sotildi',
  'accessory_sold_failed': 'Aksessuar sotish amalga oshmadi',

  // Company
  'company': 'Kompaniya',
  'enter_company': 'Kompaniyani kiriting',
  'select_company': 'Kompaniyani tanlang',
  'select_company_warning': 'Iltimos, kompaniyani tanlang',
  'not_select_company': 'Kompaniyalar mavjud emas',

  // Colors
  'colour': 'Rang',
  'select_colour': 'Rang tanlang',
  'color_black': 'Qora',
  'color_white': 'Oq',
  'color_red': 'Qizil',
  'color_blue': 'Ko‘k',
  'color_green': 'Yashil',
  'color_gold': 'Oltin',
  'color_silver': 'Kumush',
  'color_pink': 'Pushti',
  'color_purple': 'Siyohrang',
  'color_orange': 'To‘q sariq',
  'color_yellow': 'Sariq',
  'color_gray': 'Kulrang',
  'color_navy': 'To‘q ko‘k',
  'color_rose_gold': 'Pushti oltin',
  'color_champagne': 'Shampan',

  // Edit User Info
  'edit_account': 'Hisobni tahrirlash',
  'enter_name': 'Ismni kiriting',
  'enter_email': 'Elektron pochtani kiriting',
  'invalid_email_format': 'Noto‘g‘ri elektron pochta formati',
  'enter_new_password_optional': 'Yangi parolni kiriting (ixtiyoriy)',
  'password_too_short': 'Parol kamida 6 ta belgi bo‘lishi kerak',
  'user_info_updated': '✅ Foydalanuvchi ma’lumotlari muvaffaqiyatli yangilandi',
  'user_info_update_error': '❌ Xato: ',
  'profile': 'Profil',

  // Report Page
  'report_title': 'Daromadlar hisoboti',
  'total_phones': 'Telefonlar',
  'total_accessories': 'Aksessuarlar',
  'phone_profit_chart': 'Telefon foydasi diagrammasi',
  'accessory_profit_chart': 'Aksessuar foydasi diagrammasi',
  'top_selling_phones': 'Eng ko‘p sotilgan telefonlar',
  'top_selling_accessories': 'Eng ko‘p sotilgan aksessuarlar',
  'no_data_available': 'Ma’lumotlar mavjud emas',
  'currency_suffix': 'so‘m',
  'total_profit': 'Umumiy foyda',
  "no_permission": "Ruxsat yo‘q",
  "no_accessory_permission_message": "Sizda aksessuar qo‘shish uchun ruxsat mavjud emas. Iltimos, tarifingizni yangilang.",

  // Settings
  'app_setting': 'Ilova sozlamalari',
  "account_settings": "Hisob Sozlamalari",
  'setting_and_account': 'Sozlamalar va hisob',
  'setting': 'Sozlamalar',
  'dark_mode': 'Tungi rejim',
  'language': 'Til',
  'currency': 'Valyuta',
  'tariffs': 'Tariflar',
  'aboutApp': 'Ilova haqida',
  'signOut': 'Chiqish',

  // Generic Error
  'error_generic': 'Nimadir noto‘g‘ri bo‘ldi. Iltimos, qayta urinib ko‘ring.',
};
