// Uzbek
const Map<String, String> uzUZ = {
  'ok': 'OK',
  'cancel': 'Bekor qilish',
  'delete': 'O‘chirish',
  'hello': 'Salom',
  // SIGN IN PAGE
  'title': 'Yana Salom',
  'subtitle': 'Xush kelibsiz, sizni sog‘indik',
  'user_name': 'Ismingiz',
  'name_empty': 'Iltimos, ismingizni kiriting',
  'name_invalid': 'Noto‘g‘ri ism',
  'name_hint': 'Ism',
  'email': 'Email manzilingiz',
  'email_hint': 'Email kiriting',
  'email_empty': 'Iltimos, email kiriting',
  'email_invalid': 'Noto‘g‘ri email manzili',
  'password': 'Parol',
  'password_hint': 'Parol kiriting',
  'password_empty': 'Iltimos, parol kiriting',
  'recovery_password': 'Parolni tiklash',
  'sign_in': 'Kirish',
  'dont_have_account': 'Hisobingiz yo‘qmi?',
  'have_account': 'Hisobingiz bormi?',
  'sign_up': 'Ro‘yxatdan o‘tish',
  'create_account': "Hisob yaratish",
  'create_account_subtitle': 'Keling birga hisob yarataylik',
  'admin_c_title': 'Admin bilan bog‘lanish',
  'admin_c_subtitle': '"Tarifni tasdiqlash uchun admin bilan bog‘laning"',
  // TARIFF PAGE
  'tariff_title': 'Tariflar',
  'tariff_subtitle': 'Tarifingizni tanlang',
  'tariff_buy': "Sotib olish",
  'tariff_limit_title': 'Tarif Limiti',
  'tariff_limit_subtitle': 'Tarif uchun do‘kon qo‘shish limiti tugadi',
  // STORE PAGE
  'store_title': "Sizning do‘konlaringiz",
  'store_subtitle': 'Do‘kon qo‘shish uchun pastdagi tugmani bosing.',
  'store_create': 'Do‘kon yaratish',
  'store_name': 'Do‘kon nomi',
  'store_location': 'Do‘kon manzili',
  'store_name_add': 'Ism kiriting',
  'store_location_add': 'Manzil kiriting',
  'shop_delete_title': 'O‘chirish',
  'shop_delete_description': 'Do‘kon o‘chiriladimi?',
  'home_title':'Asosiy Sahifa',
};